#ifndef header_h
#define header_h

// Some defination used in code
#define OK "OK"
#define ERR "ERROR"
#define SEND_OK "SEND OK"
#define CIPCLOSE "AT+CIPCLOSE"
#define CIPSEND "AT+CIPSEND="
#define CIPSTART "AT+CIPSTART="

// Headers for HTML and XML pages
const String headerXML = "HTTP/1.1 200 OK\r\nContent-Type: text/xml\r\n\r\n";
const String headerHTML = "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nConnection: keep-alive\r\n\r\n";

// index page saved in Flash memory
const char homePage[] PROGMEM = {
  "<html>\r\n"
  "<head>\r\n"
  "<title>ESP8266</title>\r\n"
  "<script type=\"text/javascript\">\r\n"
  "window.onload=Pinstatus;\r\n"
  "function Pinstatus(){\r\n"
  "morestatus();\r\n"
  "}\r\n"
  "function morestatus(){\r\n"
  "setTimeout(morestatus, 2000);\r\n"
  "server = \"status/99\";\r\n"
  "request = new XMLHttpRequest();\r\n"
  "request.onreadystatechange = updateasyncstatus;\r\n"
  "request.open(\"PUT\", server, true);\r\n"
  "request.send(null);\r\n"
  "}\r\n"
  "function updateasyncstatus(){\r\n"
  "if ((request.readyState == 4) && (request.status == 200))\r\n"
  "{\r\n"
  "result = request.responseText;\r\n"
  "document.getElementById(\"description\").innerHTML = result;\r\n"
  "fullset = result.split(\"#\");\r\n"
  "document.getElementById(\"description\").innerHTML = fullset;\r\n"
  "for(i = 1; i < fullset.length; i++){\r\n"
  "PinPair = fullset[i];\r\n"
  "singleset = PinPair.split(\"=\");\r\n"
  "PN = singleset[0];\r\n"
  "Pinstatus = singleset[1];\r\n"
  "if (PN > 11)\r\n"
  "{\r\n"
  "ActNum = \"action\" + PN;\r\n"
  "TxtNum = \"text\" + PN;\r\n"
  "if (Pinstatus == 0)\r\n"
  "{\r\n"
  "PinAct = \"1\";\r\n"
  "text = \"Off\";\r\n"
  "}\r\n"
  "else\r\n"
  "{\r\n"
  "PinAct = \"0\";\r\n"
  "text = \"On\";\r\n"
  "}\r\n"
  "document.getElementById(ActNum).value = PinAct;\r\n"
  "document.getElementById(TxtNum).innerHTML = text;\r\n"
  "}\r\n"
  "else if (PN == 4)\r\n"
  "{\r\n"
  "ActNum = \"action\" + PN;\r\n"
  "TxtNum = \"text\" + PN;\r\n"
  "if (Pinstatus == 1)\r\n"
  "{\r\n"
  "text = \"On\";\r\n"
  "}\r\n"
  "else\r\n"
  "{\r\n"
  "text = \"Off\";\r\n"
  "}\r\n"
  "document.getElementById(ActNum).value = PinAct;\r\n"
  "document.getElementById(TxtNum).innerHTML = text;\r\n"
  "}\r\n"
  "else if (PN == 5 )\r\n"
  "{\r\n"
  "PinVal = parseInt(singleset[1]);\r\n"
  "DacNum = \"dac\" + PN;\r\n"
  "ValNum = \"valueDac\" + PN;\r\n"
  "document.getElementById(DacNum).value = PinVal;\r\n"
  "document.getElementById(ValNum).innerHTML = PinVal;\r\n"
  "}\r\n"
  "else if (PN == 6 )\r\n"
  "{\r\n"
  "PinVal = parseInt(singleset[1]);\r\n"
  "DacNum = \"dac\" + PN;\r\n"
  "ValNum = \"valueDac\" + PN;\r\n"
  "document.getElementById(DacNum).value = PinVal;\r\n"
  "document.getElementById(ValNum).innerHTML = PinVal;\r\n"
  "}\r\n"
  "else if (PN == 9 )\r\n"
  "{\r\n"
  "PinVal = parseInt(singleset[1]);\r\n"
  "DacNum = \"dac\" + PN;\r\n"
  "ValNum = \"valueDac\" + PN;\r\n"
  "document.getElementById(DacNum).value = PinVal;\r\n"
  "document.getElementById(ValNum).innerHTML = PinVal;\r\n"
  "}\r\n"
  "else if (PN == 10 )\r\n"
  "{\r\n"
  "PinVal = parseInt(singleset[1]);\r\n"
  "DacNum = \"dac\" + PN;\r\n"
  "ValNum = \"valueDac\" + PN;\r\n"
  "document.getElementById(DacNum).value = PinVal;\r\n"
  "document.getElementById(ValNum).innerHTML = PinVal;\r\n"
  "}\r\n"
  "else if (PN == 11 )\r\n"
  "{\r\n"
  "PinVal = parseInt(singleset[1]);\r\n"
  "DacNum = \"dac\" + PN;\r\n"
  "ValNum = \"valueDac\" + PN;\r\n"
  "document.getElementById(DacNum).value = PinVal;\r\n"
  "document.getElementById(ValNum).innerHTML = PinVal;\r\n"
  "}\r\n"
  "if (PN.substr(0,1) == \"A\")\r\n"
  "{\r\n"
  "PinVal = parseFloat(singleset[1]);\r\n"
  "AnalogNum = \"analog\" + PN.substr(1,2);\r\n"
  "document.getElementById(AnalogNum).value = PinVal;\r\n"
  "}\r\n"
  "}\r\n"
  "}\r\n"
  "}\r\n"
  "function sendbutton(Pin,action){\r\n"
  "document.getElementById(\"description\").innerHTML = \"Processing Button Click\";\r\n"
  "server = \"digital/\" + Pin + \"/\" + action;\r\n"
  "request = new XMLHttpRequest();\r\n"
  "request.onreadystatechange = updateasyncbutton;\r\n"
  "request.open(\"GET\", server, true);\r\n"
  "request.send(null);\r\n"
  "}\r\n"
  "function updateasyncbutton(){\r\n"
  "if ((request.readyState == 4) && (request.status == 200))\r\n"
  "{\r\n"
  "result = request.responseText;\r\n"
  "document.getElementById(\"description\").innerHTML = result;\r\n"
  "singleset = result.split(\",\");\r\n"
  "PinType = singleset[0];\r\n"
  "PinNum = singleset[1];\r\n"
  "Pinstatus = singleset[2];\r\n"
  "ActNum = \"action\" + PinNum;\r\n"
  "TxtNum = \"text\" + PinNum;\r\n"
  "if (Pinstatus == 0)\r\n"
  "{\r\n"
  "PinAct = \"1\";\r\n"
  "text = \"Off\";\r\n"
  "}\r\n"
  "else\r\n"
  "{\r\n"
  "PinAct = \"0\";\r\n"
  "text = \"On\";\r\n"
  "}\r\n"
  "document.getElementById(ActNum).value = PinAct;\r\n"
  "document.getElementById(TxtNum).innerHTML = text;\r\n"
  "document.getElementById(\"description\").innerHTML = result;\r\n"
  "}\r\n"
  "}\r\n"
  "function sendts(){\r\n"
  "document.getElementById(\"description\").innerHTML = \"Processing TS\";\r\n"
  "server = \"ts/\";\r\n"
  "request = new XMLHttpRequest();\r\n"
  "request.open(\"GET\", server, true);\r\n"
  "request.send(null);\r\n"
  "}\r\n"
  "function updateTS(){\r\n"
  "document.getElementById(\"description\").innerHTML = result;\r\n"
  "}\r\n"
  "function sendDac(Pin,value){\r\n"
  "ValNum = \"valueDac\" + Pin;\r\n"
  "document.getElementById(ValNum).innerHTML=value;\r\n"
  "document.getElementById(\"description\").innerHTML = \"Processing Slider\";\r\n"
  "server = \"dac/\" + Pin + \"/\" + value;\r\n"
  "request = new XMLHttpRequest();\r\n"
  "request.onreadystatechange = updateasyncDac;\r\n"
  "request.open(\"GET\", server, true);\r\n"
  "request.send(null);\r\n"
  "}\r\n"
  "function updateasyncDac(){\r\n"
  "if ((request.readyState == 4) && (request.status == 200))\r\n"
  "{\r\n"
  "result = request.responseText;\r\n"
  "singleset = result.split(\",\");\r\n"
  "PinType = singleset[0];\r\n"
  "PinNum = singleset[1];\r\n"
  "PinVal = parseInt(singleset[2]);\r\n"
  "DacNum = \"dac\" + PinNum;\r\n"
  "ValNum = \"valueDac\" + PinNum;\r\n"
  "document.getElementById(DacNum).value = PinVal;\r\n"
  "document.getElementById(ValNum).innerHTML = PinVal;\r\n"
  "document.getElementById(\"description\").innerHTML = result;\r\n"
  "}\r\n"
  "}\r\n"
  "</script>\r\n"
  "</head>\r\n"
  "<font face=\"Arial\">\r\n"
  "<table name=\"Table\" border=\"1\" cellpadding=\"6\">\r\n"
  "<tr> <th align=\"center\" colspan=\"5\" >Analog Input</th></tr>\r\n"
  "<tr>\r\n"
  "<td align=\"center\">\r\n"
  "A0\r\n"
  "<br>\r\n"
  "<input type=\"text\" style=\"text-align: center;\" name=\"analog\" id=\"analog0\" value=\"0\" size=\"6\" readonly/>\r\n"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "A1\r\n"
  "<br>\r\n"
  "<input type=\"text\" style=\"text-align: center;\" name=\"analog\" id=\"analog1\" value=\"0\" size=\"6\" readonly/>\r\n"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "A2\r\n"
  "<br>\r\n"
  "<input type=\"text\" style=\"text-align: center;\" name=\"analog\" id=\"analog2\" value=\"0\" size=\"6\" readonly/>\r\n"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "A3\r\n"
  "<br>\r\n"
  "<input type=\"text\" style=\"text-align: center;\" name=\"analog\" id=\"analog3\" value=\"0\" size=\"6\" readonly/>\r\n"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "A4\r\n"
  "<br>\r\n"
  "<input type=\"text\" style=\"text-align: center;\" name=\"analog\" id=\"analog4\" value=\"0\" size=\"6\" readonly/>\r\n"
  "</td>\r\n"
  "</tr>\r\n"
  "<tr> <th align=\"center\" colspan=\"5\" >Accelerometer</th></tr>\r\n"
  "<tr>\r\n"
  "<td></td>\r\n"
  "<td align=\"center\">\r\n"
  "Z\r\n"
  "<br>\r\n"
  "<input type=\"text\" style=\"text-align: center;\" name=\"analog\" id=\"analog5\" value=\"0\" size=\"6\" readonly/>\r\n"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "Y\r\n"
  "<br>\r\n"
  "<input type=\"text\" style=\"text-align: center;\" name=\"analog\" id=\"analog6\" value=\"0\" size=\"6\" readonly/>\r\n"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "X\r\n"
  "<br>\r\n"
  "<input type=\"text\" style=\"text-align: center;\" name=\"analog\" id=\"analog7\" value=\"0\" size=\"6\" readonly/>\r\n"
  "</td>\r\n"
  "<td></td>\r\n"
  "</tr>\r\n"
  "<tr> <th align=\"center\" colspan=\"5\" >Digital Input</th></tr>\r\n"
  "<tr>\r\n"
  "<td></td>\r\n"
  "<td align=\"center\">\r\n"
  "GPIO 7\r\n"
  "<br>\r\n"
  "<p id=\"text7\">Off</p>\r\n"
  "</td>\r\n"
  "<td></td>\r\n"
  "<td align=\"center\">\r\n"
  "GPIO 8\r\n"
  "<br>\r\n"
  "<p id=\"text8\">Off</p>\r\n"
  "</td>\r\n"
  "<td></td>\r\n"
  "</tr>\r\n"
  "<tr> <th align=\"center\" colspan=\"5\" >PWM Output</th></tr>\r\n"
  "<tr>\r\n"
  "<td align=\"center\">\r\n"
  "GPIO 5\r\n"
  " <br>\r\n"
  "<input type=\"hidden\" name=\"pin\" value=\"5\" id=\"pin5\" />\r\n"
  "<input type=\"range\" style=\"width: 90px; height: 30px;\" id=\"dac5\" min=\"0\" max=\"255\" value=\"0\" step=\"1\" onchange=\"sendDac(document.getElementById('pin5').value,\r\n"
  "this.value);\"/>\r\n"
  "<br>\r\n"
  "<span id=\"valueDac5\">0</span>\r\n"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "GPIO 6\r\n"
  " <br>\r\n"
  "<input type=\"hidden\" name=\"pin\" value=\"6\" id=\"pin6\" />\r\n"
  "<input type=\"range\" style=\"width: 90px; height: 30px;\" id=\"dac6\" min=\"0\" max=\"255\" value=\"0\" step=\"1\" onchange=\"sendDac(document.getElementById('pin6').value,\r\n"
  "this.value);\"/>\r\n"
  "<br>\r\n"
  "<span id=\"valueDac6\">0</span>\r\n"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "GPIO 9\r\n"
  " <br>\r\n"
  "<input type=\"hidden\" name=\"pin\" value=\"9\" id=\"pin9\" />\r\n"
  "<input type=\"range\" style=\"width: 90px; height: 30px;\" id=\"dac9\" min=\"0\" max=\"255\" value=\"0\" step=\"1\" onchange=\"sendDac(document.getElementById('pin9').value,\r\n"
  "this.value);\"/>\r\n"
  "<br>\r\n"
  "<span id=\"valueDac9\">0</span>\r\n"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "GPIO 10\r\n"
  " <br>\r\n"
  "<input type=\"hidden\" name=\"pin\" value=\"10\" id=\"pin10\" />\r\n"
  "<input type=\"range\" style=\"width: 90px; height: 30px;\" id=\"dac10\" min=\"0\" max=\"255\" value=\"0\" step=\"1\" onchange=\"sendDac(document.getElementById('pin10').value,\r\n"
  "this.value);\"/>\r\n"
  "<br>\r\n"
  "<span id=\"valueDac10\">0</span>\r\n"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "GPIO 11\r\n"
  " <br>\r\n"
  "<input type=\"hidden\" name=\"pin\" value=\"11\" id=\"pin11\" />\r\n"
  "<input type=\"range\" style=\"width: 90px; height: 30px;\" id=\"dac11\" min=\"0\" max=\"255\" value=\"0\" step=\"1\" onchange=\"sendDac(document.getElementById('pin11').value,\r\n"
  "this.value);\"/>\r\n"
  "<br>\r\n"
  "<span id=\"valueDac11\">0</span>\r\n"
  "</td>\r\n"
  "</tr>\r\n"
  "<tr> <th align=\"center\" colspan=\"5\" >Digital Output</th></tr>\r\n"
  "<tr>\r\n"
  "<td></td>\r\n"
  "<td align=\"center\">\r\n"
  "<input type=\"hidden\" name=\"pin\" value=\"4\" id=\"pin4\" />\r\n"
  "<input type=\"hidden\" name=\"action\" value=\"0\" id=\"action4\" />\r\n"
  "<button onclick=\"sendbutton(document.getElementById('pin4').value,document.getElementById('action4').value);\"/>GPIO 4</button>\r\n"
  "<p id=\"text4\">Off</p>"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "<input type=\"hidden\" name=\"pin\" value=\"12\" id=\"pin12\" />\r\n"
  "<input type=\"hidden\" name=\"action\" value=\"0\" id=\"action12\" />\r\n"
  "<button onclick=\"sendbutton(document.getElementById('pin12').value,document.getElementById('action12').value);\"/>GPIO 12</button>\r\n"
  "<p id=\"text12\">Off</p>"
  "</td>\r\n"
  "<td align=\"center\">\r\n"
  "<input type=\"hidden\" name=\"pin\" value=\"13\" id=\"pin13\" />\r\n"
  "<input type=\"hidden\" name=\"action\" value=\"0\" id=\"action13\" />\r\n"
  "<button onclick=\"sendbutton(document.getElementById('pin13').value,document.getElementById('action13').value);\"/>GPIO 13</button>\r\n"
  "<p id=\"text13\">Off</p>"
  "</td>\r\n"
  "<td></td>\r\n"
  "</tr>\r\n"
  "<tr> <th align=\"center\" colspan=\"5\" >Thing Speak</th></tr>\r\n"
  "<tr>\r\n"
  "<td></td>\r\n"
  "<td></td>\r\n"
  "<td align=\"center\">\r\n"
  "<input type=\"hidden\" name=\"TS\" value=\"0\" id=\"sendts\" />\r\n"
  "<button onclick=\"sendts();\"/>SEND TS</button>\r\n"
  "<p id=\"textTs\">TS</p>"
  "</td>\r\n"
  "<td></td>\r\n"
  "<td></td>\r\n"
  "</tr>\r\n"
  "</table>\r\n"
  "<br><br>\r\n"
  "<p id=\"description\"> - </p>\r\n"
  "</font>\r\n"
  "</html>\r\n"
};

#endif
